FROM golang:1.26-alpine AS build
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
RUN go build -o /out/server ./cmd/server

FROM debian:bookworm-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*
RUN useradd -m -d /home/app app
USER app
WORKDIR /home/app
COPY --from=build /out/server /usr/local/bin/server
EXPOSE 8080
CMD ["server"]
