namespace: gridlogger
resources:
  - ../../base
images:
  - name: ghcr.io/djumpen/gridlogger-backend
    newName: ghcr.io/djumpen/gridlogger-backend
    newTag: latest
  - name: ghcr.io/djumpen/gridlogger-frontend
    newName: ghcr.io/djumpen/gridlogger-frontend
    newTag: latest
