apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gridlogger-prod-secrets
  namespace: gridlogger
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  syncConfig:
    resyncInterval: 60s
    instantUpdates: false
  authentication:
    kubernetesAuth:
      identityId: 0ccd4957-f491-4e95-8c3c-ce268146df13
      autoCreateServiceAccountToken: false
      serviceAccountRef:
        name: infisical-service-account
        namespace: gridlogger
      secretsScope:
        projectSlug: gridlogger-7i-qn
        envSlug: prod
        secretsPath: /
        recursive: true
  managedKubeSecretReferences:
    - secretName: gridlogger-secrets
      secretNamespace: gridlogger
      creationPolicy: Orphan
