resources:
  - namespace.yaml
  - timescaledb.yaml
  - timescaledb-svc.yaml
  - backend.yaml
  - backend-svc.yaml
  - frontend.yaml
  - frontend-svc.yaml
  - https-redirect-middleware.yaml
  - ingress.yaml
